name: Test

on:
  pull_request:
    paths-ignore:
      - "README.md"

jobs:
  lint:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node:
          - '20.x'

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install npm dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  test-hugo:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        hugo:
          - '0.132.2' # .Site.IsServer deprecation ERROR
          - 'latest'
      fail-fast: true

    steps:
      - uses: actions/checkout@v4

      # https://github.com/peaceiris/actions-hugo (community action)
      - name: Run Hugo ${{ matrix.hugo }}
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ matrix.hugo }}
          fail-fast: false

      - name: Build with Hugo ${{ matrix.hugo }}
        working-directory: exampleSite
        run: |
          function ver { printf "%03d%03d%03d" $(echo "$1" | tr '.' ' '); }
          HUGO_VERSION=$(hugo version | grep -Eo '[0-9]+\.[0-9]+((\.[0-9]+)?)')
          # The option changed in 0.93.0: https://github.com/gohugoio/hugo/releases/tag/v0.93.0
          I18N_OPT=$([ $(ver $HUGO_VERSION) -lt $(ver 0.93.0) ] && echo "--i18n-warnings" || echo "--printI18nWarnings")
          # The option deprecated in v0.114.0 (WARNs >= 0.120.0): https://github.com/gohugoio/hugo/releases/tag/v0.114.0
          LOG_OPT=$([ $(ver $HUGO_VERSION) -lt $(ver 0.114.0) ] && echo "--verbose" || echo "--logLevel info")
          HUGO_THEME="Mainroad" hugo --themesDir ../.. $I18N_OPT $LOG_OPT
